config/routes.rb
Rails.application.routes.draw do

  # get 'orders/new'

  # get 'orders/index'

  # get 'orders/show'

  #get 'sessions/new'

  root "products#index"
  resources	:users, except: :index do
    resources :orders, only: [:show, :index]
  end

  resources :products do
  	resources :orders, only: [:new, :create]
  end
  resource :session, only: [:new, :create, :destroy]

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.svg"
	
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	has_many	:orders
	belongs_to 	:user
	# This does 
	# def user
	#  User.find(self.user_id)
	# end
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, length: {minimum:25}
	validates :price_in_pence, numericality: true
	

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many 	:products
	has_many	:orders

	validates 	:email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?, :user_owns?
# Look for user using sesion data

def current_user
	# if there is session data, use it to lookup user
	if session[:user_id].present?
		User.find(session[:user_id])
	else
	end
end

def current_user?
	current_user.present?
end

def require_user
	unless current_user?
		flash[:error] = "You must be logged in to do that."
		redirect_to new_session_path and return # this is a security measure
	end
end

# define an action that checks for users and makes sure the user owns something

# def require_owner(product)
# #check for current user
# #use current_user to look for belongings
# if current_user?
# 	# User current_user to look for belongings
# 	# Compare product parameter
# 	unless user_owns?(product)
# 		flash[:error] = "You can only manage products that you own"
# 		redirect_to root_path and return
# 	end
# else
# 	flash[:error] = "You have to be logged in to do that."
# 	redirect_to new_session_path and return
# end
# end 
 def user_owns?(product)
 	product.user == current_user
 end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	 before_action :require_user
	 before_action :find_product, except: [:index, :show]
	 def index
	  	#list of all previous orders for the current user
	 end

	 def show
	  	# Show the order as a receipt
	 	@product = Product.find(params["id"])
	 	@order = Order.find(params["id"])
	 end

	 def new
	 	# find_product
	 	@order = @product.orders.new
	 end

	 def create
	 	@order = @product.orders.new(order_params)
	 	if @order.save
	 		# create a charge via Stripe
	 		Stripe.api_key = "sk_test_zRxFYC7oDhf06EBkVve6eUNm"


	 		Stripe::Charge.create(
	 			:amount => @order.product.price_in_pence, 
	 			:currency => "gbp", 
	 			# :card => "tok_15O9aNAMMxpQq1PvjTSuuHSI",  
	 			:card => @order.stripe_token, # obtained with Stripe.js
	 			:description => "Charge for #{@order.product.name} purchased by #{@order.user.email}." 
	 			)
				
	  	#create a charge via Stripe
	  	#save a record of the purchase
	  	flash[:success] = "thanks for purchasing #{@product.name}, here is your receipt."
	  	#redirect to the receipt (show action)
	  	redirect_to user_order_path(current_user, @product)
	  	else
	  		flash[:error] = "Oops, something went wrong, check your details"
	  		render :new
	  	end
	  	redirect_to user_order_path(current_user)
	 end

private
def find_product
	 	@product = Product.find(params["product_id"])
end

def order_params
	params.require(:order).permit(:stripe_token, :delivery_address)
end
	


end

app/controllers/products_controller.rb
	class ProductsController < ApplicationController
	before_action	:require_user, only: [:new, :create]
	before_action 	:find_product, except: [:index,:new,:create]
	before_action	:require_owner, only: [:edit, :update, :destroy]

	def index
		# this is publicly available
		@products = Product.all
	end

	def show
		# this is publicly available
	end

	def new
		# only logged in users
		#require_user
		# if current_user?
			@product = current_user.products.new
		# else
		# 	flash[:error] = "You need to be logged in"
		# 	redirect_to new_session_path
		# end
	end

	def create
		#require_user
		# if current_user?
			#require_user
			@product = current_user.products.new(product_params)
			if @product.save
				flash[:success] = "A new product was added to the shop."
				redirect_to product_path(@product)
			else
				flash[:error] = "Oops, something went wrong, check the form and try again."
				render :new
			end
		# else
		# 	flash[:error] = "You need to be logged in"
		# 	redirect_to new_session_path

		# end
	end

	def edit
		# only logged in users and user is owner
		#require_owner(@product)
	end

	def update
		# only logged in users and user is owner
		#require_owner(@product)
		if @product.update(product_params)
			flash[:success] = "'#{@product.name}' was updated successfully."
			redirect_to product_path(@product)
		else
			flash[:error] = "Oops, something went wrong, check the form and try again."
			render :edit
		end
	end

	def destroy
				# only logged in users and user is owner
		#require_owner(@product)
		@product.destroy
			flash[:success] = "'#{@product.name}' was deleted from the shop."
		@product = nil
		redirect_to root_path

	end

private

	def product_params
		# Whitelisted form data
		params.require(:product).permit(:name,:description,:price_in_pence, :image)
	end

	def find_product
		# Query to read a record from the db
		@product = Product.find(params["id"])

	end


	def require_owner
	#check for current user
	#use current_user to look for belongings
		if current_user?
			# User current_user to look for belongings
			# Compare product parameter
			unless @product.user == current_user
				flash[:error] = "You can only manage products that you own"
				redirect_to root_path and return
			end
		else
			flash[:error] = "You have to be logged in to do that."
			redirect_to new_session_path and return
		end
	end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	# get password from params
    email = params[:session][:email]
    password = params[:session][:password]
  	# Get User from DB using email from params
  	@user = User.find_by(email: email)
    # Compare pw from params with pw from db
    if @user.present? and @user.authenticate(password)
    	# if pw==pw
    	# login
      # Unset any session data (in case of session hijacking)

      reset_session
      
      # Log in
      session[:user_id] = @user.id
      
      # tell them it worked
      flash[:success] = "Welcome back #{@user.email}."
      
      # send them home
      redirect_to root_path
  	else 
      # tell them it didn't work
      flash[:error] = "Oops, try again!"
      render :new
  	end

  end

  def destroy
    reset_session
    flash[:success] = "See you soon!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:new, :create]

  def show
  	@user = User.new
  end

  def new
  	@user = User.new
  end

  def create
  	if @user = User.new(user_params)
  		if @user.save
  			flash[:success] = "Welcome #{@user.email}!"
  			redirect_to user_path(@user)
  		else
  			flash[:error] = "Oops, that didn't work, try again"
			render :new
		end
	else
  	end
  end

  def edit
  end



  def update
  	if @user.update()
		flash[:success] = "Welcome #{@user.email}!"
		redirect_to user_path(@user) 
  	else
  			flash[:error] = "Oops, that didn't work, try again"
			render :edit
  	end
  end

  def destroy
  	@user.destroy
  	flash[:success] = "We're sorry to see you go #{@user.email} :(."

  	@user = nil
  	redirect_to root_path

end

private
	def user_params
		params.require(:user).permit(:email,:password, :password_confirmation)
	end

	def find_user
		  @user = User.find(params["id"])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<nav>
			<%= link_to root_path do %>
				<h1>Home</h1>
			<% end %>
			<!-- Only show the "Add" link to nav bar if logged in-->
			
			<div class="user-actions">
				<% if current_user? %>
					<%= link_to current_user.email, user_path(current_user) %>
					<%= link_to "Add a product", new_product_path %>
					<%= link_to "Log out", session_path, method: :delete %>
				<!-- else log in-->
				<% else %>
					<%= link_to "Log In", new_session_path %>
				<% end %>
			</div>

		</nav>
	</header>

<% flash.each do |key, value| %>
	<div class="<%= key %>">
	<p><%= value %></p>
	</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<%= simple_form_for [@product, @order] do |form| %>


<%#pk_test_6pGYg120dA22AE3Rq2qOhBV4%>



<form action="" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
</form>







<% end %>



<script type="text/javascript" src="https://js.stripe.com/v2/"></script>



<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_6pGYg120dA22AE3Rq2qOhBV4');
  // ...

	jQuery(function($) {
	  $('#new_order').submit(function(event) {
	    var $form = $(this);

	    // Disable the submit button to prevent repeated clicks
	    $form.find('button').prop('disabled', true);

	    Stripe.card.createToken($form, stripeResponseHandler);

	    // Prevent the form from submitting with the default action
	    return false;
	  });
	});

	function stripeResponseHandler(status, response) {
	  var $form = $('#new_order');

	  if (response.error) {
	    // Show the errors on the form
	    $form.find('.payment-errors').text(response.error.message);
	    $form.find('button').prop('disabled', false);
	  } else {
	    // response contains id and card, which contains additional card details
	    var token = response.id;
	    // Insert the token into the form so it gets submitted to the server
	    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
	    // and submit
	    $form.get(0).submit();
	  }
	};

</script>

app/views/orders/show.html.erb
<h1>Thanks for purchasing <%= @product.name %>, your order will be despatched within 2 working days.</h1>
<p>Shipping address : <% @order.delivery_address %></p>
<p>Your account will be debited: <% number_to_currency @product_price_in_pence.to_f%></p>
<% link_to "Continue browsing", root_path %>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :image %>
	<%= f.input :price_in_pence %>

	<%= f.button :submit %>
 <%end%>

app/views/products/edit.html.erb
<h2>Edit your product</h2>
<h3><%= @product %></h3>

<%= render "form" %>

app/views/products/index.html.erb
<h2>Products</h2>

<section class="products">

	<% @products.each do |product| %>

		<div class="product">

			<div class="image">
				<%= link_to product_path(product) do %>
					<%= image_tag product.image.url(:thumb) %>
				<% end %>

			</div>


		
			<div class = "info">
				<%= link_to product_path(product) do %>
					<h4><%= product.name %></h4>
				<% end %>
				<p><%= product.description.truncate(70, separator: /\s/) %></p>
				<small><%= number_to_currency(product.price_in_pence.to_f/100, unit: "£") %></small>
			</div>
		<div class="actions">
			<!-- if logged in AND  user is owner -->
			<% if current_user? and user_owns?(product) %>
				<%= link_to "Edit", edit_product_path(product) %>
				<%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "are you sure you want to delete that?"} %>
			<% else %>
			<% end %>
			<!--  -->
		</div>
	</div>
	
<% end %>

</section>

app/views/products/new.html.erb
<h2>Submit a new product below</h2>

<%= render "form" %>

app/views/products/show.html.erb

<section class="product">
	<h2><%= @product.name %></h2>
	<p><%= image_tag @product.image.url(:medium) %></p>
	<p><%= @product.description %></p>
	<small>£<%= @product.price_in_pence/100 %> </small></p>
	<%= link_to "Buy", new_product_order_path(@product) %>
	<p><small>For more information contact <%= mail_to @product.user.email %>.</small></p>
</section>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= simple_form_for @user do |f| %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>

	<%= f.button :submit, "Sign up" %>

<% end %>

<small>Already signed up? <%= link_to "Log in", new_session_path %></small>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>